 

// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `Database`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=LOCALHOST;Initial Catalog=NorthWind;Integrated Security=True`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`

// -----------------------------------------------------------------------------------------
// Failed to read database schema - Cannot open database "NorthWind" requested by the login. The login failed. Login failed for user 'MicrosoftAccount\jebb.burditt@gmail.com'.
// -----------------------------------------------------------------------------------------

 